// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * CommandService handles storing and retrieving commands
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddCommand adds a new command to storage
 * @param {string} content
 * @returns {$CancellablePromise<$models.Command>}
 */
export function AddCommand(content) {
    return $Call.ByID(3452678840, content).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * DeleteCommand removes a command by ID
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteCommand(id) {
    return $Call.ByID(1888656992, id);
}

/**
 * GetCommands returns all stored commands
 * @returns {$CancellablePromise<$models.Command[]>}
 */
export function GetCommands() {
    return $Call.ByID(2230805162).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.Command.createFrom;
const $$createType1 = $Create.Array($$createType0);
